# Generated by Django 5.2.4 on 2025-12-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani_app', '0002_rename_payment_txn_id_idx_mtaani_app__transac_35b769_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='url_key',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='url_key',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
